// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetLanguageCount(ctx context.Context) (int64, error)
	GetLanguages(ctx context.Context) ([]Language, error)
}

var _ Querier = (*Queries)(nil)
